### PR TITLE
Add views

### PR DESCRIPTION
**Pull request by topeogunleye**
### Added Changes
- Used preprocessed HTML file with embedded Ruby code.
- Used Layouts and templates for shared content.
- Implemented the design from the sneak peek wireframes.
- Used methods that I created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

### CODE REVIEW

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @topeogunleye 👋, 

Good job so far!

## Highlights
- Has correct logic for `index` and `show` actions in Users Controllers ✔️ 
- Has correct logic for `index` and `show` actions in Posts Controllers ✔️ 
- Set up View files for the `User` controller correctly ✔️ 
- Set up View files for the `Post` controller correctly ✔️
- Has dedicated routes for each View file ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### I am making this comment here because I can not highlight the required piece of code in the files changed section 

- [ ] Kindly delete the migrations files that were created when you attempted to use `Devise` and `CanCanCan` gems for this milestone. The reason for this is I can't create a user successfully if they are not deleted and they are not required for this milestone. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] You can also consider using partial for rendering common views in your User view files. Making use of partials is one of the Ruby on Rails best practices because it ensures that you do not repeat codes in the view files. You can read this [documentation](https://guides.rubyonrails.org/layouts_and_rendering.html) for a better understanding. Kindly consider this suggestion. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by topeogunleye** [comment]
> Hi @topeogunleye wave,
> 
> Good job so far!
> 
> ## Highlights
> * Has correct logic for `index` and `show` actions in Users Controllers heavy_check_mark
> * Has correct logic for `index` and `show` actions in Posts Controllers heavy_check_mark
> * Set up View files for the `User` controller correctly heavy_check_mark
> * Set up View files for the `Post` controller correctly heavy_check_mark
> * Has dedicated routes for each View file heavy_check_mark
> 
> However, there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes 
> #### I am making this comment here because I can not highlight the required piece of code in the files changed section
> * [ ]  Kindly delete the migrations files that were created when you attempted to use `Devise` and `CanCanCan` gems for this milestone. The reason for this is I can't create a user successfully if they are not deleted and they are not required for this milestone. +1
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> * [ ]  You can also consider using partial for rendering common views in your User view files. Making use of partials is one of the Ruby on Rails best practices because it ensures that you do not repeat codes in the view files. You can read this [documentation](https://guides.rubyonrails.org/layouts_and_rendering.html) for a better understanding. Kindly consider this suggestion. +1
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@Gambit142, Thank you so much for your wonderful review :+1:

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @topeogunleye, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
You have done a great job working on the requested changes 👍

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly commit the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Deepakdanger — APPROVED** [review]
Hi @topeogunleye, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding proper steps in the README file to run the project from clone to running the server. You have mentioned some of the steps but that doesn't help the recruiter, that's why always try to add all the steps with full clarity.

```
$ git clone https://github.com/topeogunleye/blog-app-rails.git
$ cd blog-app-rails
$ bundle
$ rails db:setup
$ rails s
```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> Hi @topeogunleye,
> 
> ### Status: Approved 
> Your project is complete! There is nothing else to say other than... it's time to merge it ship Congratulations! tada
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * Adding proper steps in the README file to run the project from clone to running the server. You have mentioned some of the steps but that doesn't help the recruiter, that's why always try to add all the steps with full clarity.
> 
> ```
> $ git clone https://github.com/topeogunleye/blog-app-rails.git
> $ cd blog-app-rails
> $ bundle
> $ rails db:setup
> $ rails s
> ```
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for your kind review. I will implement the optional changes immediately.

**Pull request merged**
